package io.github.fmweigl.yetanothermealsapp.recipe.data.database

import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

internal const val DATABASE_FILE_NAME = "recipes.db"

/** The recipe feature's database on the device. Its schemas are exported to the module's `schemas/`. */
@Database(entities = [FavoriteRecipeEntity::class], version = 1)
@ColumnTypeConverters(RecipeColumnTypeConverters::class)
@ConstructedBy(RecipeDatabaseConstructor::class)
internal abstract class RecipeDatabase : RoomDatabase() {
    abstract fun favoriteRecipeDao(): FavoriteRecipeDao
}

/** Implemented by Room's compiler for each platform. */
// The actual objects are generated by KSP, which the IDE and detekt don't see.
@Suppress("KotlinNoActualForExpect")
internal expect object RecipeDatabaseConstructor : RoomDatabaseConstructor<RecipeDatabase> {
    override fun initialize(): RecipeDatabase
}

/** Builds the database with the same driver and query threads on every platform. */
internal fun RoomDatabase.Builder<RecipeDatabase>.buildRecipeDatabase(): RecipeDatabase =
    setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()
